services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    ports:
      - "2121:2121"
  frontend:
    build:
      context: ./social-sport-app
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
